export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_STREAM = 'CREATE_STREAM';
export const FETCH_STREAMS = 'FETCH_STREAMS';
export const FETCH_STREAM = 'FETCH_STREAM';
export const DELETE_STREAM = 'DELETE_STREAM';
export const EDIT_STREAM = 'EDIT_STREAM';

export const CREATE_STUDENT = 'CREATE_STUDENT';
export const FETCH_STUDENTS	= 'FETCH_STUDENTS';
export const FETCH_STUDENT	= 'FETCH_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

export const CREATE_SUBJECT = 'CREATE_SUBJECT';
export const FETCH_SUBJECTS	= 'FETCH_SUBJECTS';
export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const FETCH_QUESTIONS	= 'FETCH_QUESTIONS';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION'; 

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const FETCH_ANSWERS = 'FETCH_ANSWERS';
